[package]
name = "tests"
version = "0.1.0"
authors = ["Microsoft"]
edition = "2018"

[dependencies]
winrt = { path = ".." }

[dev-dependencies]
futures = "0.3"

[build-dependencies]
winrt = { path = ".." }

[package.metadata.winrt.dependencies]
"Microsoft.Windows.SDK.Contracts" = "10.0.19041.1"